apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: demo-policy-placementbinding
  namespace: acm-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: demo-policy-placement
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: deny-unapproved-deployments
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: enforce-drift-demo
